version: "3.5"

services:

    mail:

        image: tvial/docker-mailserver
        networks:
            front:
                aliases:
                    - mail.docker

        configs:
            - source: mail-accounts2
              target: /tmp/docker-mailserver/postfix-accounts.cf
        environment:
            - OVERRIDE_HOSTNAME=mail.lubeck.apinf.cloud
        deploy:
            replicas: 1
            restart_policy:
                condition: any

################################################################################
# Configs
################################################################################

configs:

    mail-accounts2:
        file: ../config/postfix-accounts.cf


networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16
