version: "3.5"

services:

    mongo:
        image: mongo:3.6        
        expose:
            - 27017
        networks:
            - mongo
        volumes:
            - /opt/mongo-data:/data/db
        deploy:
            restart_policy:
                condition: any

networks:

    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
