version: "3.5"

services:

    wirecloudnginx:
        image: nginx:latest
        volumes:
            - /opt/wirecloud-static:/var/www/static:ro
        configs:
            - source: wirecloud_nginx
              target: /etc/nginx/nginx.conf
        depends_on:
            - wirecloud
        networks:
            - wirecloud
            - front
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    wirecloud:
        image: fiware/wirecloud
        environment:
            - DEBUG=False
            - BASE_DOMAIN=lubeck.apinf.cloud
            - ALLOWED_HOSTS=dashboards.lubeck.apinf.cloud localhost
            - DB_HOST=wirecloud_postgres
            - DB_PORT=5432
            - FORWARDED_ALLOW_IPS=*
            - ELASTICSEARCH2_URL=http://wirecloud_elasticsearch:9200/
            - MEMCACHED_LOCATION=wirecloud_memcached:11211
            - FIWARE_IDM_SERVER=https://accounts.lubeck.apinf.cloud
            - SOCIAL_AUTH_FIWARE_KEY=<key>
            - SOCIAL_AUTH_FIWARE_SECRET=<key>
        depends_on:
            - wirecloud_memcached
            - wirecloud_postgres
        volumes:
            - /opt/wirecloud-data:/opt/wirecloud_instance/data
            - /opt/wirecloud-static:/var/www/static
        networks:
            - front
            - wirecloud
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    wirecloud_elasticsearch:
        image: elasticsearch:2.4
        volumes:
            - /opt/wirecloud-elasticsearch:/usr/share/elasticsearch/data
        networks:
            - wirecloud
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    wirecloud_postgres:
        image: postgres:9.6
        volumes:
            - /opt/wirecloud-postgres:/var/lib/postgresql/data
        networks:
            - wirecloud
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    wirecloud_memcached:
        image: memcached:1
        command: memcached -m 2048m
        networks:
            - wirecloud
        deploy:
            # This is required to fix some connection problems
            endpoint_mode: dnsrr
            replicas: 1
            restart_policy:
                condition: any

configs:

    wirecloud_nginx:
        file: ../config/wirecloud-nginx.conf

networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16

    wirecloud:
        driver: overlay
        ipam:
            config:
                - subnet: 172.43.0.0/16
